packages:
  - 'apps/*'
  - 'packages/*'

allowBuilds:
  '@prisma/engines': true
  esbuild: true
  msgpackr-extract: true
  prisma: true

minimumReleaseAgeExclude:
  - eslint@10.12.0
  - lucide-react@1.51.0
