import { z } from 'zod'

/**
 * The record the gateway emits for every tool call and (sampled) auth failure. It travels as
 * JSON (through BullMQ or straight to Postgres), so it holds only plain values, and it is
 * already masked: nothing downstream needs to scrub it again.
 */

export const LOG_ERROR_CLASSES = [
  // tools/call
  'VALIDATION',
  'UNKNOWN_TOOL',
  'NO_BASE_URL',
  'REQUEST_BUILD',
  'CREDENTIAL',
  'UPSTREAM_4XX',
  'UPSTREAM_5XX',
  'REDIRECT',
  'TIMEOUT',
  'TOO_LARGE',
  'BLOCKED',
  'UNREACHABLE',
  'RATE_LIMITED',
  'INTERNAL',
  // authentication
  'AUTH_MISSING',
  'AUTH_INVALID',
  'AUTH_WRONG_PROJECT',
] as const

export type LogErrorClass = (typeof LOG_ERROR_CLASSES)[number]

export const ERROR_MESSAGE_MAX_CHARS = 300

export const logEventSchema = z
  .object({
    /** Generated by the gateway when the event happens. It becomes the row's primary key, so a redelivered batch is skipped. */
    id: z.string().min(1).max(64),
    kind: z.enum(['TOOL_CALL', 'AUTH_FAILURE']),
    /** Known for tool calls (the authenticated project). */
    projectId: z.string().min(1).max(64).optional(),
    /** Set for auth failures, where only the URL's slug is known; the writer resolves it to a project. */
    projectSlug: z.string().min(1).max(64).optional(),
    apiKeyId: z.string().min(1).max(64).nullable(),
    toolId: z.string().min(1).max(64).nullable(),
    toolName: z.string().max(128).nullable(),
    /** Masked and truncated arguments. `{}` for auth failures. */
    input: z.record(z.string(), z.unknown()),
    upstreamStatus: z.number().int().min(100).max(599).nullable(),
    latencyMs: z.number().int().min(0),
    success: z.boolean(),
    errorClass: z.enum(LOG_ERROR_CLASSES).nullable(),
    errorMessage: z.string().max(ERROR_MESSAGE_MAX_CHARS).nullable(),
    responseBytes: z.number().int().min(0).nullable(),
    /** Epoch milliseconds when the call happened (not when the row is written). */
    timestamp: z.number().int().min(0),
  })
  .refine((e) => e.projectId !== undefined || e.projectSlug !== undefined, {
    message: 'an event needs a projectId or a projectSlug',
  })

export type LogEvent = z.infer<typeof logEventSchema>

const URL_LIKE = /\b[a-z][a-z0-9+.-]*:\/\/\S*|(?:^|\s)\/\/[^\s/]+\S*/gi
const QUERY_STRING = /\?\S*/g

/**
 * Make free text safe to store: first line only, no URLs (a query-parameter credential is
 * appended to the URL we call, and a redirect's Location can carry one), no query strings,
 * at most {@link ERROR_MESSAGE_MAX_CHARS} characters.
 */
export function sanitizeErrorMessage(text: string): string {
  // Bound the work first: a hostile message must not cost more than its prefix.
  const firstLine = (text.slice(0, 2000).split(/\r?\n/, 1)[0] ?? '').trim()
  const cleaned = firstLine.replace(URL_LIKE, '[url]').replace(QUERY_STRING, '?[query]').trim()
  return cleaned.length > ERROR_MESSAGE_MAX_CHARS ? `${cleaned.slice(0, ERROR_MESSAGE_MAX_CHARS - 1)}…` : cleaned
}
